### PR TITLE
fixed: use types::transaction::SignedTransaction; instead of transaction::SignedTransaction; 

### PR DESCRIPTION
**Pull request by RyanKung**
When compile with `1.31.0 (339d9f9c8 2018-11-16)` on my Gentoo

I got:
```
error[E0432]: unresolved import `transaction`
  --> rpc/src/v1/impls/personal.rs:44:5
   |
44 | use transaction::SignedTransaction;
   |     ^^^^^^^^^^^ did you mean `types::transaction`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `parity-rpc`.
```

That is what this pull request for

### CODE REVIEW

**Comment by RyanKung** [comment]
[clabot:check]

**Comment by RyanKung** [comment]
[clabot:check]

**Comment by niklasad1** [comment]
FYI, introduced by https://github.com/paritytech/parity-ethereum/pull/10051/files#diff-3f161f90cabddef291e29887755cb3e6 weird that it passed all the tests....
