### ISSUE TITLE
Parity 'stable' branch fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by coinerrr** [paritytech/parity-ethereum#9304]
**I'm running:**

Parity Stable as of 08/06/18
Ubuntu 14.04 
rustc 1.28
Installed from source
It's half synced
Network: ethereum 

**I'm updating Parity from source. I've ran the following commands:**

`git pull`
`rustup update`
`cargo clean`
`cargo build --release`

**Things to note**

After running the above commands I deleted my local 'stable' branch and refetched it remotely. This resulted in the same build errors. Another thing to note is that the 'master' branch builds just fine.

**The build errors:**

`error[E0283]: type annotations required: cannot resolve \`std::string::String: std::convert::AsRef<_>\`
  --> util/network-devp2p/src/service.rs:35:91
   |
35 |                 info!(target: "network", "Public node URL: {}", Colour::White.bold().paint(public_url.as_ref()));
   |                                                                                                       ^^^^^^

error: aborting due to previous error

For more information about this error, try \`rustc --explain E0283`.
error: Could not compile \`ethcore-network-devp2p\`.
`

**Comment by Tbaut** [comment]
Please make sure you have installed [all the dependencies](https://wiki.parity.io/Setup#dependencies). I could build master without error.

**Comment by coinerrr** [comment]
Please read my description. It says that 'master' can be built without a problem. My problem is that 'stable' can not be built. It fails.

**Comment by Tbaut** [comment]
I could build the `stable` branch as well.

**Comment by lrettig** [comment]
I'm getting the same error today trying to build 1.11.8 stable on Amazon Linux (CentOS), all dependencies installed.
