### PR TITLE
Unbreak parity-rpc build on rust -stable

### PR DESCRIPTION
**Pull request by reyk**
```
   Compiling parity-rpc v1.12.0 (file:///home/reyk/devel/parity-ethereum/rpc)
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> rpc/src/v1/helpers/light_fetch.rs:628:19
    |
628 |                         if let Some(vm::Error::OutOfGas) = executed.exception {
    |                                     ^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `parity-rpc`.

```

### CODE REVIEW

**Comment by reyk** [comment]
[clabot:check]

**Comment by niklasad1** [comment]
Hey, thanks but it works on Rust stable 1.30. Please update your toolchain instead

**Comment by reyk** [comment]
It's a simple fix that works on both versions, why speaks against merging it?

I'm using OpenBSD 6.4 that ships rust 1.29.2 - OpenBSD -current includes 1.30.x or later but the next OpenBSD -stable release (6.5) will only be released in about 6 months.

**Comment by reyk** [comment]
Thanks!
